import React from 'react';
import { ArrowRight, Layers3, LockKeyhole, ScanSearch, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import TopBar from '../components/TopBar.jsx';

const SOURCES = [
  { label: 'NIST: Migration to PQC FAQ and cryptographic inventory guidance', url: 'https://pages.nist.gov/nccoe-migration-post-quantum-cryptography/' },
  { label: 'NIST SP 1800-38B: Quantum Readiness—Cryptographic Discovery', url: 'https://www.nccoe.nist.gov/sites/default/files/2023-12/pqc-migration-nist-sp-1800-38b-preliminary-draft.pdf' },
  { label: 'NIST: Post-quantum cryptography standards and migration resources', url: 'https://www.nist.gov/pqc' },
];

export default function News() {
  return <div className="news-page"><style>{`
    @import url('https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=switzer@400,500,600&display=swap');
    .news-page { min-height:100vh; background:#0a0d12; color:#e8eaef; font-family:'Switzer',system-ui,sans-serif; }.news-page * { box-sizing:border-box; }.news-hero,.news-content { max-width:900px; margin:0 auto; padding-left:32px; padding-right:32px; }.news-hero { padding-top:80px; padding-bottom:50px; border-bottom:1px solid #1b2129; }.news-kicker { color:#c9a227; font:12px 'IBM Plex Mono',monospace; letter-spacing:.13em; text-transform:uppercase; }.news-hero h1 { font:600 clamp(34px,5vw,58px)/1.08 'Clash Display',sans-serif; max-width:780px; margin:18px 0; }.news-dek { max-width:680px; color:#a9b1bf; font-size:17px; line-height:1.65; }.news-content { padding-top:52px; padding-bottom:100px; max-width:820px; }.news-content h2 { font:600 26px 'Clash Display',sans-serif; margin:54px 0 13px; }.news-content p,.news-content li { color:#a9b1bf; font-size:15px; line-height:1.75; }.news-content strong { color:#e8eaef; }.news-flow { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin:30px 0; }.news-flow div { background:#12161d; border:1px solid #1b2129; padding:15px; border-radius:8px; font-size:12px; color:#c3c8d1; }.news-flow svg { display:block; color:#c9a227; margin-bottom:12px; }.news-callout { border-left:3px solid #c9a227; padding:15px 18px; background:#12161d; color:#c3c8d1; line-height:1.65; margin:26px 0; }.news-refs { margin-top:42px; padding:22px; border:1px solid #1b2129; border-radius:10px; background:#12161d; }.news-refs h2 { margin-top:0; font-size:20px; }.news-refs a { color:#d5b441; text-decoration:none; }.news-refs li { font-size:13px; margin:9px 0; }.news-cta { display:inline-flex; gap:8px; align-items:center; color:#191308; background:#c9a227; text-decoration:none; border-radius:6px; padding:11px 15px; font-weight:600; margin-top:26px; } @media(max-width:680px){.news-hero,.news-content{padding-left:20px;padding-right:20px}.news-flow{grid-template-columns:repeat(2,1fr)}}
  `}</style><TopBar /><article><header className="news-hero"><span className="news-kicker">Semicolon research note · PQC readiness</span><h1>The hard part of post-quantum migration is knowing what you have.</h1><p className="news-dek">Quantum readiness starts with visibility. Semicolon turns cryptographic discovery into an inventory, an explainable risk view, and a practical route from a scanned file to next actions.</p></header><main className="news-content">
    <h2>The problem we are solving</h2><p>Cryptography is embedded in certificates, application code, services, configuration, identities, and vendor dependencies. That distribution makes it difficult to produce one current account of where public-key cryptography is used, what depends on it, and which changes should come first. NIST describes a cryptographic inventory as the foundation for managing cryptographic risk consistently and preparing systems for post-quantum cryptography (PQC).</p>
    <h2>Why this matters in the real world</h2><p>A migration is not simply an algorithm swap. Teams need to find affected assets, understand service dependencies, test interoperability, and plan change without interrupting critical operations. Data that must remain confidential for a long time can be exposed to “harvest now, decrypt later” risk if it is collected before quantum-capable attacks become practical. That makes an inventory-and-prioritisation process useful today, even while migration timelines vary by organisation.</p>
    <h2>How Semicolon is different</h2><p>Semicolon does more than list algorithms. It connects discovery to context: the asset, location, detector confidence, risk band, dependency view, recommended next step, and PQC action status. That means a security team can move from an uploaded input to a reportable remediation plan rather than a disconnected set of findings.</p>
    <div className="news-flow"><div><ScanSearch size={18}/>1. Discover<br />Scan uploaded material</div><div><Layers3 size={18}/>2. Classify<br />Normalise assets and context</div><div><ShieldCheck size={18}/>3. Prioritise<br />Apply a risk band and action plan</div><div><LockKeyhole size={18}/>4. Report<br />Export the scan summary</div></div>
    <h2>From input to output</h2><p>After a user uploads a file, Semicolon identifies cryptographic evidence and presents the results for that scan: a crypto inventory, risk breakdown, asset topology, current-versus-projected risk chart, readiness view, and recommended actions. The dashboard deliberately remains empty before a scan completes so it never presents example findings as a user’s actual security posture.</p>
    <h2>Architecture and risk engine</h2><p>The product experience is organised around distinct layers: ingestion and scanning, discovery and normalisation, a contextual risk engine, recommendation logic, reporting, and the dashboard. The risk view is designed to consider algorithm type, exposed location, asset category, detector confidence, and remediation urgency. These are risk-informed assessments for planning—not guarantees of security and not a replacement for expert validation.</p>
    <h2>Security, privacy, and crypto-agility</h2><p>Semicolon is designed around data minimisation, auditable results, controlled report access, and avoiding the need to expose secret key material in an inventory. Its PQC view focuses on the operational work that makes change possible: identifying quantum-vulnerable public-key cryptography, tracking assets that require action, prioritising the most consequential work, and keeping the future migration path adaptable as standards and environments evolve.</p>
    <div className="news-callout"><strong>Our story:</strong> Semicolon exists to make cryptographic exposure legible. We want teams to replace uncertainty and spreadsheet hunts with a clear, prioritised path to crypto-agility.</div>
    <section className="news-refs"><h2>Research notes</h2><p>The article is informed by the sources below. They support the case for discovery, inventory, and migration planning; Semicolon’s product descriptions are not claims of certification or guaranteed outcomes.</p><ol>{SOURCES.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ol><Link to="/references" className="news-cta">See the full reference library <ArrowRight size={15}/></Link></section>
  </main></article></div>;
}
